server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 3
    password:
      timeout: 10000
      pool:
        # 最大空闲连接数
        max-idle: 20
        # 可以分配的最大连接数
        max-active: 50
        # 阻塞的最大时间
        max-wait: 10000
        # 最小空闲连接数
        min-idle: 10
